server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /opensearch/ {
        proxy_pass http://opensearch.utterai-observability.svc.cluster.local:9200/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
